minor fixes in the commands
archway-network/archway-docs pull request #57
Opened 2022-03-01 07:28 UTC by mojtaba-esk

2022-03-01 11:47 UTC, aelesbao requested changes

2022-03-01 11:47 UTC, aelesbao commented on docs/participate/staking.md
> +First remove any archway node data if there is any:
```suggestion
First, remove any archway node data if there is any:
```

2022-03-01 11:47 UTC, aelesbao commented on docs/participate/staking.md
> +*Note: This example connects to the `constantine` test node. Make sure to connect to the right network.
```suggestion
*Note:* This example connects to the `constantine` test node. Make sure to connect to the correct network.
```

2022-03-01 11:48 UTC, aelesbao approved these changes

2022-03-01 11:53 UTC, merged

2022-03-03 19:57 UTC, drewstaylor commented
This PR is built and published on the server now 😎